language: node_js
node_js:
- 14.16
deploy:
  provider: heroku
  api_key:
    secure: m7D8SoOx18HXE1HGNqa8sfM8vc2Qq1V2pE7TrsQOKgxdMMD2Dh1FPwY6LSavXPxW5xt6fk6TqEkbD7DSMlEJ7sJBhwmDNQVSfYmLZ0TNW5guVeoPws64C59vR4S5kDhlpJ/vkGdtJPh5SokQrgFDX58x7oKKSAqF3tj1zYQxijiqlZz80dEc3lc2kclaCRdIOVHShFJ655r9R0PL931dXqBEC9Pw9ugZXJy1hS97TAdcgIHM/rqB766Bbcvar0IxKnKsGy61sSn2U7aPFugZbLMbijcX5zkWyAEMXDd0PLUAru7/EFiZ088PFKMxZj7kRaT8qZadHpHevKW/yd3Ob6M9d2wbjCGAGPdUjZmosSomD6JO75igcZDGt0H6K2QxTM13CBlQytaxOzTtBv9Ju+X4tyJHJBEv8MZrAC8E8gTSw6mmI7UlJgothTvJ5Qw27HnVt5LJmiy6jFL3M1K6KmG541eG5/LCthn8EoLz1rBxXGurae6pi6QHeZmeqRqpUn/PICtIG2i79vhsN6OxqvwY6Mo2zoI2MFfWc/C0cYlZ4iC9rll5mPf0wiCd4JY388PJTc8brP5xiPLpGhB9Kq5UJC9uRUr0ZtiEKu2cU5dx80L/4DMVtHewc6orNMR3Xs939ANIEw0osgKqrx4/F/XteHVtBkj94TLcmQFpgos=
  strategy: git
  app:
    master: finance-calendar
